name = "cf-one-apex"
main = "src/index.ts"
compatibility_date = "2026-07-21"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = false
keep_vars = true

[[routes]]
pattern = "lunarlab.uk"
custom_domain = true

[[routes]]
pattern = "20100823.xyz"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "cf-one"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "00000000000000000000000000000000"
