import { escapeHtml } from './security';

const BASE_CSS = String.raw`
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--bg:#fffbfe;--card:#fff;--text:#1d1b20;--muted:#625b71;--line:#cac4d0;--accent:#6750a4;--accentText:#fff;--soft:#eaddff;--danger:#ba1a1a} @media(prefers-color-scheme:dark){:root{--bg:#141218;--card:#211f26;--text:#e6e1e5;--muted:#cac4d0;--line:#49454f;--accent:#d0bcff;--accentText:#381e72;--soft:#4f378b;--danger:#ffb4ab}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);line-height:1.5}a{color:inherit}.shell{max-width:1120px;margin:auto;padding:20px 18px 70px}.top{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:24px}.brand{text-decoration:none;font-weight:700}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:18px}.stack{display:grid;gap:12px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.between{justify-content:space-between}.button{border:0;border-radius:999px;padding:10px 16px;background:var(--soft);color:var(--text);cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.button.primary{background:var(--accent);color:var(--accentText)}.button.danger{color:var(--danger)}input,textarea,select{width:100%;border:1px solid var(--line);border-radius:12px;padding:10px 12px;background:transparent;color:inherit}textarea{min-height:110px;resize:vertical}label{display:grid;gap:6px;font-weight:600}.help{font-size:.86rem;color:var(--muted);font-weight:400}.pill{display:inline-flex;padding:5px 9px;border-radius:999px;background:var(--soft);font-size:.84rem}.metric{font-size:1.7rem;font-weight:700}.question{padding:14px 0;border-top:1px solid var(--line)}.question:first-child{border-top:0}.choices{display:grid;gap:8px;margin-top:10px}.choice{display:flex;gap:9px;align-items:flex-start}.choice input{width:auto;margin-top:5px}.bar{height:10px;border-radius:999px;background:var(--line);overflow:hidden}.bar>span{display:block;height:100%;background:var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.hidden{display:none!important}.notice{padding:12px 14px;border-radius:14px;background:var(--soft)}@media(max-width:600px){.shell{padding:14px 12px 60px}.card{border-radius:16px;padding:14px}.top{align-items:flex-start}}
`;

function page(title: string, body: string, script: string): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escapeHtml(title)}</title><style>${BASE_CSS}</style></head><body>${body}<script type="module" src="${script}"></script></body></html>`;
}

export function testStudioPage(siteName: string): string {
  return page(`Test · ${siteName}`, `<main class="shell"><header class="top"><a class="brand" href="/">← ${escapeHtml(siteName)}</a><div class="row"><span class="pill">Test Studio</span><a class="button" href="/test">公开测试</a></div></header><section class="stack"><div><div class="muted">小测试 / 心理测试 / 问卷 / 投票</div><h1>Test</h1><p class="muted">从模板开始，也可以自己定义题目、结果和隔离运行的 JavaScript。</p></div><div id="studio" class="stack" aria-live="polite"><div class="card">正在加载…</div></div></section></main>`, '/assets/test-studio.js');
}

export function testDirectoryPage(siteName: string): string {
  return page(`公开测试 · ${siteName}`, `<main class="shell"><header class="top"><a class="brand" href="/">← ${escapeHtml(siteName)}</a><a class="button" href="/app/test">创建测试</a></header><h1>公开测试</h1><p class="muted">心理测试、问卷、题目和投票。</p><section id="directory" class="grid"><div class="card">正在加载…</div></section></main>`, '/assets/test-runner.js');
}

export function testRunPage(siteName: string, slug: string): string {
  return page(`Test · ${siteName}`, `<main class="shell"><header class="top"><a class="brand" href="/test">← 全部测试</a><span class="pill">${escapeHtml(siteName)}</span></header><section id="runner" class="stack" data-slug="${escapeHtml(slug)}"><div class="card">正在加载…</div></section></main>`, '/assets/test-runner.js');
}

export const TEST_STUDIO_JS = String.raw`
const root=document.querySelector('#studio');let session=null;let mine=[];
const templates={
 psychology:{title:'心理测试',description:'按选项计分并映射到结果区间。',definition:{questions:[{id:'q1',text:'遇到新环境时，我通常会主动探索。',type:'single',options:[{id:'a',text:'很符合',score:3},{id:'b',text:'比较符合',score:2},{id:'c',text:'不太符合',score:1},{id:'d',text:'完全不符合',score:0}]}]},results:[{key:'high',min:2,title:'探索型',description:'你更倾向于主动接触变化。'},{key:'low',max:1,title:'谨慎型',description:'你更倾向于先观察再行动。'}]},
 survey:{title:'问卷',description:'收集选择题和文本回答。',definition:{questions:[{id:'q1',text:'你最希望改进哪一项？',type:'single',options:[{id:'a',text:'功能'},{id:'b',text:'界面'},{id:'c',text:'性能'}]},{id:'q2',text:'还有什么想说的？',type:'text'}]},results:[]},
 quiz:{title:'题目',description:'支持带分值的选择题。',definition:{questions:[{id:'q1',text:'1 + 1 = ?',type:'single',options:[{id:'a',text:'2',score:1},{id:'b',text:'3',score:0}]}]},results:[{key:'perfect',min:1,title:'答对了',description:'Nice.'},{key:'try',max:0,title:'再试一次',description:'看看题目再想想。'}]},
 poll:{title:'投票',description:'最简单的单题投票。',definition:{questions:[{id:'vote',text:'你更喜欢哪个？',type:'single',options:[{id:'a',text:'A'},{id:'b',text:'B'}]}]},results:[]}
};
function h(tag,attrs,...children){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==false&&v!=null)e.setAttribute(k,String(v));}for(const c of children.flat())if(c!=null)e.append(c instanceof Node?c:document.createTextNode(String(c)));return e}function clear(){root.replaceChildren()}function field(label,name,value,type='text',help=''){const el=type==='textarea'?h('textarea',{name}):h('input',{name,type});el.value=value??'';return h('label',null,label,el,help?h('span',{class:'help',text:help}):null)}async function api(path,opt={}){const headers=new Headers(opt.headers||{});headers.set('accept','application/json');if(opt.body&&typeof opt.body!=='string'){headers.set('content-type','application/json');opt.body=JSON.stringify(opt.body)}if(session?.csrf&&!['GET','HEAD'].includes((opt.method||'GET').toUpperCase()))headers.set('x-csrf-token',session.csrf);const r=await fetch(path,{credentials:'same-origin',...opt,headers});const b=await r.json();if(!r.ok)throw new Error(b.error||'请求失败');return b}function parse(text,fallback){try{return JSON.parse(text)}catch{return fallback}}function slug(t){return String(t||'').toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff-]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function templatePicker(){return h('div',{class:'grid'},...Object.entries(templates).map(([key,t])=>h('button',{class:'card',type:'button',onclick:()=>editor(null,key)},h('strong',{text:t.title}),h('p',{class:'muted',text:t.description}))));}
function list(){clear();root.append(h('div',{class:'row between'},h('div',null,h('h2',{text:'我的测试'}),h('div',{class:'muted',text:'创建、发布并查看统计。'})),h('button',{class:'button primary',text:'新建',onclick:()=>{clear();root.append(templatePicker())}})));if(!mine.length)root.append(h('div',{class:'card',text:'还没有测试。点“新建”从模板开始。'}));for(const t of mine)root.append(h('div',{class:'card'},h('div',{class:'row between'},h('div',null,h('strong',{text:t.title}),h('div',{class:'muted',text:t.kind+' · '+t.status+' · /test/'+t.slug})),h('div',{class:'row'},h('a',{class:'button',href:'/test/'+t.slug,target:'_blank',text:'预览'}),h('button',{class:'button',text:'编辑',onclick:()=>editor(t)}),h('button',{class:'button',text:'统计',onclick:()=>stats(t)}))))}
function editor(existing,key){const base=existing||templates[key||'survey'];clear();const form=h('form',{class:'stack'},h('div',{class:'row between'},h('h2',{text:existing?'编辑测试':'新建 '+base.title}),h('button',{class:'button',type:'button',text:'返回',onclick:list})),field('标题','title',base.title),field('Slug','slug',existing?.slug||slug(base.title),'text','公开地址 /test/slug'),field('说明','description',base.description,'textarea'),h('label',null,'类型',h('select',{name:'kind'},...['psychology','survey','quiz','poll'].map(k=>h('option',{value:k,text:k})))),field('题目 JSON','definition',JSON.stringify(base.definition,null,2),'textarea','questions: [{id,text,type,options:[{id,text,score?}]}]'),field('结果 JSON','results',JSON.stringify(base.results,null,2),'textarea','可按 min/max 匹配总分；poll/survey 可以留空。'),field('自定义 JavaScript','customJs',existing?.customJs||'','textarea','在 opaque-origin sandbox iframe 中执行。定义 window.cfTestHook = ({test,answers,score}) => ({resultKey,score})。'),h('label',null,'从 .js 文件载入',h('input',{type:'file',accept:'.js,text/javascript',onchange:async e=>{const f=e.target.files?.[0];if(f)form.elements.customJs.value=await f.text()}})),h('div',{class:'row'},h('button',{class:'button primary',type:'submit',text:'保存草稿'}),existing?h('button',{class:'button',type:'button',text:existing.status==='published'?'关闭':'发布',onclick:()=>changeStatus(existing,existing.status==='published'?'closed':'published')}):null,existing?h('button',{class:'button danger',type:'button',text:'删除',onclick:()=>remove(existing)}):null));form.elements.kind.value=base.kind||key||'survey';form.addEventListener('submit',async e=>{e.preventDefault();try{const body={title:form.elements.title.value,slug:form.elements.slug.value,description:form.elements.description.value,kind:form.elements.kind.value,definition:parse(form.elements.definition.value,null),results:parse(form.elements.results.value,null),customJs:form.elements.customJs.value};if(!body.definition||!body.results)throw new Error('题目或结果 JSON 格式错误');if(existing)await api('/api/test/'+existing.id,{method:'PATCH',body});else await api('/api/test',{method:'POST',body});await load();list()}catch(err){alert(err.message)}});root.append(form)}
async function changeStatus(t,status){try{await api('/api/test/'+t.id,{method:'PATCH',body:{status}});await load();list()}catch(e){alert(e.message)}}async function remove(t){if(!confirm('删除“'+t.title+'”？答卷和统计也会删除。'))return;try{await api('/api/test/'+t.id,{method:'DELETE'});await load();list()}catch(e){alert(e.message)}}
async function stats(t){clear();try{const s=await api('/api/test/'+t.id+'/stats');const m=s.summary||{};const rate=m.started?Math.round(m.completed/m.started*100):0;root.append(h('div',{class:'row between'},h('h2',{text:t.title+' · 统计'}),h('button',{class:'button',text:'返回',onclick:list})),h('div',{class:'grid'},...[[m.visitors,'访客'],[m.started,'开始'],[m.completed,'完成'],[rate+'%','完成率']].map(([v,l])=>h('div',{class:'card'},h('div',{class:'metric',text:v??0}),h('div',{class:'muted',text:l})))),h('div',{class:'card'},h('h3',{text:'结果分布'}),...(s.resultDistribution||[]).map(r=>h('div',{class:'row between'},h('span',{text:r.result_key||'未分类'}),h('strong',{text:r.count})))),h('div',{class:'card'},h('h3',{text:'各题分布'}),...Object.entries(s.questionDistribution||{}).map(([q,vals])=>h('div',{class:'question'},h('strong',{text:q}),...Object.entries(vals).sort((a,b)=>b[1]-a[1]).map(([a,n])=>h('div',{class:'row between'},h('span',{text:a}),h('span',{text:n})))))))}catch(e){root.append(h('div',{class:'card',text:e.message}))}}
async function load(){mine=(await api('/api/test/mine')).tests||[]}async function start(){try{session=(await api('/api/auth/session')).session;if(!session){clear();root.append(h('div',{class:'card'},h('h2',{text:'需要登录'}),h('a',{class:'button primary',href:'/app/login',text:'前往登录'})));return}await load();list()}catch(e){clear();root.append(h('div',{class:'card',text:e.message}))}}start();
`;

export const TEST_RUNNER_JS = String.raw`
const directory=document.querySelector('#directory');const runner=document.querySelector('#runner');function h(tag,attrs,...children){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==false&&v!=null)e.setAttribute(k,String(v));}for(const c of children.flat())if(c!=null)e.append(c instanceof Node?c:document.createTextNode(String(c)));return e}async function api(path,opt={}){const headers=new Headers(opt.headers||{});headers.set('accept','application/json');if(opt.body&&typeof opt.body!=='string'){headers.set('content-type','application/json');opt.body=JSON.stringify(opt.body)}const r=await fetch(path,{...opt,headers});const b=await r.json();if(!r.ok)throw new Error(b.error||'请求失败');return b}function visitor(){let v=sessionStorage.getItem('cf-test-visitor');if(!v){v=crypto.randomUUID().replaceAll('-','');sessionStorage.setItem('cf-test-visitor',v)}return v}function calc(test,answers){let score=0;for(const q of test.definition?.questions||[]){const selected=answers[q.id];for(const o of q.options||[]){if(Array.isArray(selected)?selected.includes(o.id):selected===o.id)score+=Number(o.score||0)}}let result=null;for(const r of test.results||[]){if((r.min==null||score>=r.min)&&(r.max==null||score<=r.max)){result=r;break}}return{score,resultKey:result?.key||'',result}}async function custom(test,answers,base){if(!test.hasCustomJs)return base;const {customJs}=await api('/api/test/public/'+encodeURIComponent(test.slug)+'/custom-js');if(!customJs)return base;return new Promise(resolve=>{const frame=document.createElement('iframe');frame.sandbox='allow-scripts';frame.hidden=true;const token=crypto.randomUUID();frame.srcdoc='<script>window.addEventListener("message",async(e)=>{if(!e.data||e.data.token!=="'+token+'")return;try{'+customJs+';const fn=window.cfTestHook;const out=typeof fn==="function"?await fn(e.data.payload):{};parent.postMessage({token:"'+token+'",out},"*")}catch(error){parent.postMessage({token:"'+token+'",error:String(error)},"*")}})<\/script>';document.body.append(frame);const timer=setTimeout(()=>{frame.remove();resolve(base)},1500);function on(e){if(e.source!==frame.contentWindow||e.data?.token!==token)return;clearTimeout(timer);window.removeEventListener('message',on);frame.remove();resolve(e.data.out&&typeof e.data.out==='object'?{...base,...e.data.out}:base)}window.addEventListener('message',on);frame.addEventListener('load',()=>frame.contentWindow.postMessage({token,payload:{test,answers,score:base.score}},'*'),{once:true})})}
async function showDirectory(){try{const data=await api('/api/test/public/list');directory.replaceChildren();const short=location.hostname==='test.lunarlab.uk';if(short)directory.append(h('a',{class:'card',href:'/mf01sm'},h('span',{class:'pill',text:'legacy'}),h('h2',{text:'Cognition & orientation test'}),h('p',{class:'muted',text:'mf01sm / migrated to Test'})));for(const t of data.tests||[])directory.append(h('a',{class:'card',href:(short?'':'/test')+'/'+t.slug},h('span',{class:'pill',text:t.kind}),h('h2',{text:t.title}),h('p',{class:'muted',text:t.description||'打开测试'})));if(!(data.tests||[]).length&&!short)directory.append(h('div',{class:'card',text:'暂时没有已发布的测试。'}))}catch(e){directory.replaceChildren(h('div',{class:'card',text:e.message}))}}
async function showRunner(){const slug=runner.dataset.slug;const vid=visitor();try{const {test}=await api('/api/test/public/'+encodeURIComponent(slug)+'?visitor='+encodeURIComponent(vid));runner.replaceChildren(h('div',null,h('span',{class:'pill',text:test.kind}),h('h1',{text:test.title}),h('p',{class:'muted',text:test.description})));if(test.status==='closed'){runner.append(h('div',{class:'notice',text:'这个测试已经结束，当前只能查看。'}));return}const form=h('form',{class:'card stack'});for(const q of test.definition?.questions||[]){const box=h('section',{class:'question'},h('strong',{text:q.text}));if(q.type==='text')box.append(h('textarea',{name:q.id,placeholder:'输入回答'}));else{const choices=h('div',{class:'choices'});for(const o of q.options||[]){const type=q.type==='multi'?'checkbox':'radio';choices.append(h('label',{class:'choice'},h('input',{type,name:q.id,value:o.id}),h('span',{text:o.text})))}box.append(choices)}form.append(box)}form.append(h('button',{class:'button primary',type:'submit',text:'提交'}));let started=false;form.addEventListener('change',async()=>{if(started)return;started=true;api('/api/test/public/'+encodeURIComponent(slug)+'/start',{method:'POST',body:{visitorId:vid}}).catch(()=>{})},{once:true});form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const answers={};for(const q of test.definition?.questions||[]){if(q.type==='multi')answers[q.id]=fd.getAll(q.id);else answers[q.id]=fd.get(q.id)||''}let outcome=calc(test,answers);outcome=await custom(test,answers,outcome);await api('/api/test/public/'+encodeURIComponent(slug)+'/submit',{method:'POST',body:{visitorId:vid,answers,resultKey:outcome.resultKey||'',score:Number.isFinite(outcome.score)?outcome.score:null}});runner.replaceChildren(h('div',{class:'card stack'},h('span',{class:'pill',text:'已完成'}),h('h1',{text:outcome.result?.title||'感谢参与'}),h('p',{class:'muted',text:outcome.result?.description||'你的回答已经提交。'}),Number.isFinite(outcome.score)?h('div',null,'得分：',h('strong',{text:outcome.score})):null,h('a',{class:'button',href:'/test',text:'看看其他测试'}))});runner.append(form)}catch(e){runner.replaceChildren(h('div',{class:'card',text:e.message}))}}
if(directory)showDirectory();if(runner)showRunner();
`;
