import presentationRuntime from './presentation-runtime.js';

const GENDER_FIELD = String.raw`<div class="field gender-self-field"><label>2. 你的性别认同更接近哪里？</label><div class="note tiny gender-note">先选择你在“男性 ↔ 非二元 ↔ 女性”上的位置；身份标签可以多选，也可以不选。跨性别不是这条轴上的固定一点，例如跨性别女性可以选择“女性”并同时选择“跨性别”。</div><div class="gender-spectrum-scroll"><div id="genderSpectrum" class="gender-spectrum" role="radiogroup" aria-label="性别位置"><button class="choice gender-position" data-gender-position="男性" role="radio" aria-checked="false" type="button">男性</button><button class="choice gender-position" data-gender-position="偏男性" role="radio" aria-checked="false" type="button">偏男性</button><button class="choice gender-position" data-gender-position="男性-非二元之间" role="radio" aria-checked="false" type="button">男 / 非二元之间</button><button class="choice gender-position" data-gender-position="非二元" role="radio" aria-checked="false" type="button">非二元</button><button class="choice gender-position" data-gender-position="非二元-女性之间" role="radio" aria-checked="false" type="button">非二元 / 女之间</button><button class="choice gender-position" data-gender-position="偏女性" role="radio" aria-checked="false" type="button">偏女性</button><button class="choice gender-position" data-gender-position="女性" role="radio" aria-checked="false" type="button">女性</button></div></div><div class="gender-axis-labels" aria-hidden="true"><span>男性</span><span>非二元</span><span>女性</span></div><div class="gender-outside"><button class="choice gender-position" data-gender-position="轴外/无性别" role="radio" aria-checked="false" type="button">不在这条轴上 / 无性别</button></div><div class="gender-tags-heading"><b>身份标签</b><span class="muted tiny">可多选 · 可不选</span></div><div id="genderTags" class="gender-tags"><button class="choice gender-tag" data-gender-tag="跨性别" aria-pressed="false" type="button">跨性别 <small>Trans</small></button><button class="choice gender-tag" data-gender-tag="非二元" aria-pressed="false" type="button">非二元 <small>Non-binary</small></button><button class="choice gender-tag" data-gender-tag="性别酷儿" aria-pressed="false" type="button">性别酷儿 <small>Genderqueer</small></button><button class="choice gender-tag" data-gender-tag="性别流动" aria-pressed="false" type="button">性别流动 <small>Genderfluid</small></button><button class="choice gender-tag" data-gender-tag="无性别" aria-pressed="false" type="button">无性别 <small>Agender</small></button><button class="choice gender-tag" data-gender-tag="探索中" aria-pressed="false" type="button">探索中 <small>Questioning</small></button></div><label class="gender-other-label" for="genderOther">其他自我描述 <span class="muted tiny">可选</span></label><input id="genderOther" maxlength="28" autocomplete="off" placeholder="例如 demigirl / bigender / 自定义描述"><div data-field="selfGender" hidden><button id="genderValueProxy" class="choice" data-value="" type="button" aria-hidden="true" tabindex="-1"></button></div></div>`;

const GENDER_CSS = String.raw`<style id="mf01sm-gender-spectrum-ux">
.gender-self-field{gap:12px}.gender-note{margin:2px 0 4px}.gender-spectrum-scroll{overflow-x:auto;overscroll-behavior-inline:contain;padding:16px 2px 4px;scrollbar-width:thin}.gender-spectrum{position:relative;display:grid;grid-template-columns:repeat(7,minmax(92px,1fr));gap:8px;min-width:720px;padding-top:16px}.gender-spectrum::before{content:"";position:absolute;left:6%;right:6%;top:5px;height:4px;border-radius:999px;background:linear-gradient(90deg,color-mix(in srgb,var(--accent) 72%,var(--surface-4)),var(--accent),color-mix(in srgb,var(--accent) 72%,var(--surface-4)))}.gender-position{position:relative;text-align:center!important;display:flex;align-items:center;justify-content:center;min-height:58px!important;padding:10px 8px!important}.gender-spectrum .gender-position::before{content:"";position:absolute;top:-18px;left:50%;width:12px;height:12px;border:3px solid var(--surface-2);border-radius:999px;background:var(--accent);transform:translateX(-50%);box-shadow:0 0 0 1px var(--accent)}.gender-position.active{border-color:var(--accent)!important;background:var(--accent-container)!important;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--accent) 56%,transparent)!important}.gender-axis-labels{display:grid;grid-template-columns:1fr 1fr 1fr;color:var(--muted);font-size:.82rem;padding:0 4px}.gender-axis-labels span:nth-child(2){text-align:center}.gender-axis-labels span:last-child{text-align:right}.gender-outside{display:flex;margin-top:2px}.gender-outside .gender-position{width:auto;min-width:min(100%,260px)}.gender-tags-heading{display:flex;align-items:baseline;gap:10px;margin-top:10px}.gender-tags{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:9px}.gender-tag{display:flex;align-items:baseline;justify-content:space-between;gap:8px;min-height:54px!important}.gender-tag small{font-size:.76rem;color:var(--muted);font-weight:600}.gender-tag.active small{color:inherit;opacity:.8}.gender-other-label{margin-top:6px}.gender-self-field #genderOther{margin-top:-4px}@media(max-width:520px){.gender-spectrum-scroll{margin-inline:-8px;padding-inline:8px}.gender-spectrum{min-width:680px}.gender-tags{grid-template-columns:1fr 1fr}.gender-tag{padding:12px!important;display:block;text-align:left!important}.gender-tag small{display:block;margin-top:2px}.gender-outside .gender-position{width:100%}}@media(max-width:380px){.gender-tags{grid-template-columns:1fr}}
</style>`;

const GENDER_JS = String.raw`<script id="mf01sm-gender-spectrum-js">(()=>{const spectrum=document.getElementById('genderSpectrum');const proxy=document.getElementById('genderValueProxy');if(!spectrum||!proxy)return;const positions=[...document.querySelectorAll('[data-gender-position]')];const tags=[...document.querySelectorAll('[data-gender-tag]')];const other=document.getElementById('genderOther');let position='';const selected=new Set();const sync=()=>{if(!position)return;const extra=(other?.value||'').trim();const parts=[position,...selected];if(extra)parts.push('其他:'+extra.slice(0,28));proxy.dataset.value=parts.join('｜').slice(0,80);proxy.click();};positions.forEach(btn=>btn.addEventListener('click',()=>{position=btn.dataset.genderPosition||'';positions.forEach(x=>{const active=x===btn;x.classList.toggle('active',active);x.setAttribute('aria-checked',active?'true':'false');});sync();}));tags.forEach(btn=>btn.addEventListener('click',()=>{const tag=btn.dataset.genderTag||'';if(!tag)return;if(selected.has(tag))selected.delete(tag);else selected.add(tag);const active=selected.has(tag);btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active?'true':'false');sync();}));other?.addEventListener('input',sync);})();</script>`;

function replaceGenderField(html) {
  const pattern = /<div class="field"><label>2\. 你目前的性别认同更接近？<\/label><div class="grid" data-field="selfGender">[\s\S]*?<\/div><\/div>(?=<div class="field"><label>3\.)/;
  if (!pattern.test(html)) return html;
  html = html.replace(pattern, GENDER_FIELD);
  html = html.replace('</head>', `${GENDER_CSS}</head>`);
  html = html.replace('</body>', `${GENDER_JS}</body>`);
  return html;
}

async function enhanceGenderIdentity(request, env, ctx) {
  const response = await presentationRuntime.fetch(request, env, ctx);
  if (request.method !== 'GET') return response;
  const type = response.headers.get('content-type') || '';
  if (!type.includes('text/html')) return response;
  const url = new URL(request.url);
  if (url.pathname !== '/') return response;
  const original = await response.text();
  const body = replaceGenderField(original);
  const headers = new Headers(response.headers);
  headers.delete('content-length');
  return new Response(body, { status: response.status, statusText: response.statusText, headers });
}

export default {
  fetch(request, env, ctx) {
    return enhanceGenderIdentity(request, env, ctx);
  }
};
